version: "3"
services:
  eureka-microservice:
      image: stefankruk/eureka-microservice
      environment:
        SERVICE_HOST: eureka-microservice
      ports:
        - 8761:8761

  config-microservice:
    image: stefankruk/config-microservice
    environment:
      SERVICE_HOST: config-microservice
      REGISTRY_HOST: eureka-microservice
      CONFIG_LOCATION: /var/tmp/config
    volumes:
      - ./config/:/var/tmp/config
    ports:
      - 8888:8888

  gateway-microservice:
    image: stefankruk/gateway-microservice
    environment:
      REGISTRY_HOST: eureka-microservice
      UAA_HOST: authentication-microservice
    depends_on:
      - eureka-microservice
      - config-microservice
      - authentication-microservice
    ports:
      - 80:80

  authentication-microservice:
    image: stefankruk/authentication-microservice
    environment:
      REGISTRY_HOST: eureka-microservice
    depends_on:
      - eureka-microservice
      - config-microservice
    ports:
      - 9999:9999

  resource-microservice:
    image: stefankruk/resource-microservice
    environment:
      REGISTRY_HOST: eureka-microservice
    depends_on:
      - eureka-microservice
      - config-microservice
    ports:
      - 10000:10000

  account-microservice:
    image: stefankruk/account-microservice
    environment:
      REGISTRY_HOST: eureka-microservice
    depends_on:
      - eureka-microservice
      - config-microservice
    ports:
      - 10002:10002

  accountclient-microservice:
    image: stefankruk/accountclient-microservice
    environment:
      REGISTRY_HOST: eureka-microservice
    depends_on:
      - eureka-microservice
      - config-microservice
    ports:
      - 10003:10003

