server:
  port: 8888

spring:
  profiles:

  application:
        name: config-microservice
    mvc:
        view:
            prefix: /
            suffix: .jsp

    cloud:
      config:
        server:
          bootstrap: true
          git:
            uri: file:../config/

spring.profiles.active=native
spring.cloud.config.server.native.searchLocations=${user.dir}/src/main/resources/configs

endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true
    health:
        sensitive: false

eureka:
    host: localhost
    instance:
        health-check-url: http://${eureka.host}:${server.port}/
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
    client:
        serviceUrl:
            defaultZone: http://${eureka.host}:8761/eureka/