server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-microservice
  mvc:
    view:
      prefix: /
      suffix: .jsp

  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: ../config/

endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true
    health:
        sensitive: false

eureka:
  instance:
    hostname: localhost
    port: 8761
    health-check-url: http://${eureka.host}:${server.port}/
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: ./config

server:
  port: ${SERVICE_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}