spring:
  profiles:
    include: native
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: ${CONFIG_LOCATION}

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${REGISTRY_HOST}
    port: 8761
    health-check-url: http://${eureka.host}:${server.port}/
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/