spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: ../config/

eureka:
  instance:
    hostname: localhost
    port: 8761
    health-check-url: http://${eureka.host}:${server.port}/
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/