server:
  port: 9999
  context-path: /uaa
  use-forward-headers: false

keystore.key: mySecretKey

security:
  basic:
    enabled: false
  user:
    password: password


logging:
  level:
    org.springframework.security: DEBUG