server:
  port: 10000

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: mySecretKey
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiPrn6FoEyOclHN/5oXrQ1wM1pFTK8hRC5MqodmNDQ+HNhGNk2GokbqVZB0+Tsndx6aCnLyO5cRosYI7ARsPTDh5MeUNpVKroimxGlZ6Ojffs+b9lxGasoIBlzjbDqGgolRHHdwimGzM0RltFYql6NSqhKKhpAdzQxSYqKSITOqODo1ENNms79M3YjcItLKAHc4C0aianYelQPm2jY2HrqMtp09ckTF/uccpAXTkcA9FcSzFLPiNbk/lNrqtsNNQ7o4ZquWni/wlpJi6U/Ue/H8W9EQUg7YgxGVV2/4AcWJTsNhR0gQresPzi0A1ll6RRVOEh1v0pjzYCdxhfPTGpJwIDAQAB
          -----END PUBLIC KEY-----