server:
    port: 10000

endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true
    health:
        sensitive: false

eureka:
    host: localhost
    instance:
        health-check-url: http://${eureka.host}:${server.port}/
    client:
        serviceUrl:
            defaultZone: http://${eureka.host}:8761/eureka/

welcome:
  message: Hello Stefan